# Generated by Django 4.1.4 on 2022-12-25 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TUNIZO', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Espece',
            new_name='Especes',
        ),
        migrations.CreateModel(
            name='TuniZooUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sexe', models.CharField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'other')], max_length=1)),
                ('Followers', models.ManyToManyField(to='TUNIZO.tunizoouser')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[(0, 'Photo'), (1, 'Video'), (2, 'Texte')], max_length=1)),
                ('Description', models.TextField(max_length=200)),
                ('Likes', models.IntegerField()),
                ('UserPublications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TUNIZO.tunizoouser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=200)),
                ('MsgReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='TUNIZO.tunizoouser')),
                ('MsgSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='TUNIZO.tunizoouser')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=200)),
                ('Likes', models.IntegerField()),
                ('Publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TUNIZO.publication')),
                ('UserCommentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TUNIZO.tunizoouser')),
            ],
        ),
    ]
