# Generated by Django 4.1.4 on 2022-12-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUNIZO', '0002_rename_espece_especes_tunizoouser_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunizoouser',
            name='Sexe',
            field=models.CharField(choices=[('1', 'FEMALE'), ('2', 'MALE')], default='1', max_length=2),
        ),
    ]
