# Generated by Django 4.1.4 on 2022-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUNIZO', '0005_rename_userpublications_publication_userpublication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especes',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='Type',
        ),
        migrations.AddField(
            model_name='especes',
            name='TYPES',
            field=models.CharField(choices=[('0', 'Annimal'), ('1', 'Tree')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='publication',
            name='TYPEPUB',
            field=models.CharField(choices=[('0', 'Photo'), ('1', 'Video'), ('2', 'Texte')], default='2', max_length=2),
        ),
    ]
