# Generated by Django 4.1.4 on 2022-12-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUNIZO', '0006_remove_especes_type_remove_publication_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Montant', models.IntegerField()),
                ('UserDonation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TUNIZO.tunizoouser')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EspeceAdopted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TUNIZO.especes')),
                ('UserAdoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TUNIZO.tunizoouser')),
            ],
        ),
    ]
