# Generated by Django 4.1.4 on 2022-12-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUNIZO', '0007_donation_adoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='especes',
            name='Refuge',
            field=models.CharField(default='Hi', max_length=100),
        ),
    ]
