# Generated by Django 4.1.4 on 2022-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUNIZO', '0008_especes_refuge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especes',
            name='Refuge',
            field=models.CharField(default='S.O.S ANIMALS', max_length=100),
        ),
    ]
