# Generated by Django 4.1.4 on 2022-12-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUNIZO', '0009_alter_especes_refuge'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='Image',
            field=models.ImageField(blank=True, upload_to='src/'),
        ),
    ]
