# Generated by Django 4.1.4 on 2023-01-17 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUNIZO', '0012_remove_publication_userpublication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 11, 27, 3, 11846)),
        ),
    ]
